### ISSUE TITLE
分像图片时，不传thumbnail或者传空，app崩溃

### ISSUE THREAD

**Issue by hyz1992** [OpenFlutter/fluwx#15]
fluwx版本号：0.1.8
复现方式，example下，share_image_page.dart，98行，不传thumbnail或者传空。
错误堆栈：

`
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference
at android.graphics.Bitmap.createBitmap(Bitmap.java:835)
at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
at android.graphics.Bitmap.createBitmap(Bitmap.java:739)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:615)
at com.jarvan.fluwx.utils.ThumbnailCompressUtil.createScaledBitmap(ThumbnailCompressUtil.java:163)
at com.jarvan.fluwx.utils.WeChatThumbnailUtil.createScaledBitmapWithRatio(WeChatThumbnailUtil.java:132)
at com.jarvan.fluwx.utils.WeChatThumbnailUtil.compress(WeChatThumbnailUtil.java:120)
at com.jarvan.fluwx.utils.WeChatThumbnailUtil.thumbnailForCommon(WeChatThumbnailUtil.java:97)
at com.jarvan.fluwx.handler.FluwxShareHandler$getThumbnailByteArrayCommon$2.doResume(FluwxShareHandler.kt:157)
`

**Comment by JarvanMo** [comment]
@hyz1992 `0.1.9`已经修复这个问题了。
