### ISSUE TITLE
ios 使用问题 wechat not installed

### ISSUE THREAD

**Issue by yxfmlbb** [OpenFlutter/fluwx#16]
完整代码：
```dart
import 'package:flutter/material.dart';
import 'package:fluwx/fluwx.dart';
void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Fluwx fluwx;
  @override
  void initState() {
    super.initState();
    Fluwx.register(appId: 'wxaf***a8471d***',doOnIOS: true,doOnAndroid: true,enableMTA: false);
    fluwx = Fluwx();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('testFluwx'),
      ),
      body: new Center(
        child: new Column(          
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[            
            RaisedButton(onPressed: (){
              fluwx.share(
                  WeChatShareTextModel(
                  text: "text from fluwx",
                  transaction: "transaction",
                  scene: WeChatScene.SESSION
                )
              );
            },child: Text('share'),)
          ],
        ),
      ),      
    );
  }
}
```
异常信息：
```
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
**PlatformException(wechat not installed, wechat not installed, null)**
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
<asynchronous suspension>
#2      Fluwx.share (package:fluwx/src/fluwx_class.dart:91:29)
<asynchronous suspension>
#3      _MyHomePageState.build.<anonymous closure> (file:///Users/yxfmlbb/AndroidStudioProjects/flutter_testfluwx/lib/main.dart:39:21)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#17     _invoke1 (dart:ui/hooks.dart:153:13)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:107:5)
```

请指教，感谢！
创建工程时没有勾选swift 和 kotlin 
IOS 真机运行

**Comment by JarvanMo** [comment]
安装微信了？

**Comment by yxfmlbb** [comment]
安装了的。手机是iphone6 sp IOS 是12.0版本

**Comment by yxfmlbb** [comment]
使用flutter 里面 share 插件是可以微信分享的。但是只能分享链接。

**Comment by JarvanMo** [comment]
最新的系统啊。我升级一下微信SDK试试。

**Comment by JarvanMo** [comment]
分享应该都是好用的。除非1.8.2不兼容ios12，但pod现在还没有1.8.3。

**Comment by JarvanMo** [comment]
@yxfmlbb 忽然想起来，你在info.plist添加URLSchema了吗

**Comment by JarvanMo** [comment]
1、iOS 9系统策略更新，限制了http协议的访问，此外应用需要在“Info.plist”中将要使用的URL Schemes列为白名单，才可正常检查其他应用是否安装。
受此影响，当你的应用在iOS 9中需要使用微信SDK的相关能力（分享、收藏、支付、登录等）时，需要在“Info.plist”里增加如下代码：
<key>LSApplicationQueriesSchemes</key>
<array>
<string>weixin</string>
</array>
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key>
<true/>
</dict>

**Comment by JarvanMo** [comment]
<key>LSApplicationQueriesSchemes</key>
<array>
<string>weixin</string>
</array>
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key>
<true/>
</dict>

**Comment by JarvanMo** [comment]
https://github.com/OpenFlutter/fluwx/blob/master/doc/QUESTIONS.md  看看这个吧。

**Comment by yxfmlbb** [comment]
好的谢谢

**Comment by JarvanMo** [comment]
https://github.com/OpenFlutter/fluwx/blob/master/doc/QUESTIONS_CN.md

**Comment by JarvanMo** [comment]
可以入我们的QQ群：892398530
