### ISSUE TITLE
图片传url地址时，创建文件失败

### ISSUE THREAD

**Issue by yy1300326388** [OpenFlutter/fluwx#17]
### java.io.IOException: open failed: ENOENT (No such file or directory)

```java
W/System.err(29211): java.io.IOException: open failed: ENOENT (No such file or directory)
W/System.err(29211): 	at java.io.File.createNewFile(File.java:939)
W/System.err(29211): 	at java.io.File.createTempFile(File.java:1004)
W/System.err(29211): 	at java.io.File.createTempFile(File.java:961)
W/System.err(29211): 	at com.jarvan.fluwx.utils.WeChatThumbnailUtil.downloadImage(WeChatThumbnailUtil.java:234)
W/System.err(29211): 	at com.jarvan.fluwx.utils.WeChatThumbnailUtil.thumbnailForCommon(WeChatThumbnailUtil.java:95)
W/System.err(29211): 	at com.jarvan.fluwx.handler.FluwxShareHandler$getThumbnailByteArrayCommon$2.doResume(FluwxShareHandler.kt:157)
W/System.err(29211): 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
W/System.err(29211): 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:150)
W/System.err(29211): 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:14)
W/System.err(29211): 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1388)
W/System.err(29211): 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:251)
W/System.err(29211): 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:845)
W/System.err(29211): 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1674)
W/System.err(29211): 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1629)
W/System.err(29211): 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
W/System.err(29211): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err(29211): 	at libcore.io.Posix.open(Native Method)
W/System.err(29211): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W/System.err(29211): 	at java.io.File.createNewFile(File.java:932)
W/System.err(29211): 	... 14 more
```

**Comment by yy1300326388** [comment]
是我图片地址的问题：https://mmbiz.qlogo.cn/mmbiz_png/ZvsBf7icE27KrUNv3uzIgIqdkaSIFxAt8QTDSd2vJqyricicUnWtjSzHH5cmkB9g0ia1DH4oBibAlWtKdshJBra16gQ/0?wx_fmt=png
我稍后提一个pr，来修复这个问题

**Comment by JarvanMo** [comment]
@yy1300326388 好的。还有分享图片的地方。

**Comment by JarvanMo** [comment]
@yy1300326388 这是OpenFlutter QQ交流群，892398530

**Comment by JarvanMo** [comment]
0.2.1修复了 #18
