### ISSUE TITLE
demo工程分享图片崩溃 asset 路径错误

### ISSUE THREAD

**Issue by wanderingGuy** [OpenFlutter/fluwx#241]
崩溃日志：
```
E/AndroidRuntime( 9920): FATAL EXCEPTION: main
E/AndroidRuntime( 9920): Process: net.sourceforge.simcpux, PID: 9920
E/AndroidRuntime( 9920): java.io.FileNotFoundException: flutter_assets//logo.png
E/AndroidRuntime( 9920): 	at android.content.res.AssetManager.openAssetFd(Native Method)
E/AndroidRuntime( 9920): 	at android.content.res.AssetManager.openFd(AssetManager.java:655)
E/AndroidRuntime( 9920): 	at com.jarvan.fluwx.handlers.FluwxShareHandlerEmbedding$assetFileDescriptor$1.invoke(FluwxShareHandler.kt:40)
E/AndroidRuntime( 9920): 	at com.jarvan.fluwx.handlers.FluwxShareHandlerEmbedding$assetFileDescriptor$1.invoke(FluwxShareHandler.kt:29)
E/AndroidRuntime( 9920): 	at com.jarvan.fluwx.io.WeChatImage$Companion.createWeChatImage(WeChatImages.kt:132)
E/AndroidRuntime( 9920): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$DefaultImpls.readThumbnailByteArray(FluwxShareHandler.kt:254)
E/AndroidRuntime( 9920): 	at com.jarvan.fluwx.handlers.FluwxShareHandler$shareImage$1.invokeSuspend(FluwxShareHandler.kt:129)
E/AndroidRuntime( 9920): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 9920): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)

```

分享图片调用代码：
```
  void _shareImage() {
    source = WeChatImage.network('https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1534614311230&di=b17a892b366b5d002f52abcce7c4eea0&imgtype=0&src=http%3A%2F%2Fimg.mp.sohu.com%2Fupload%2F20170516%2F51296b2673704ae2992d0a28c244274c_th.png');
    thumbnail = WeChatImage.asset('assets://images/logo.png');

    shareToWeChat(WeChatShareImageModel(source, thumbnail: thumbnail));
  }
```

路径为 //images/logo.png 也是崩溃，请问是路径配置问题吗？

**Comment by JarvanMo** [comment]
Duplicate of #214
