### ISSUE TITLE
WeChatImage.network空指针异常

### ISSUE THREAD

**Issue by lvyandev** [OpenFlutter/fluwx#292]
**Describe the bug**

WeChatImage.network空指针异常

shareContent.shareUrl: ` http://img-bak.shike1.com/o_1e60vtps51cc51ngj1iin1usat9m9.png`

```dart
 final fluwx.WeChatShareWebPageModel shareModel =
                    fluwx.WeChatShareWebPageModel(
                  shareContent.shareUrl,
                  title: shareContent.shareTitle,
                  description: shareContent.shareMessage,
                  thumbnail: fluwx.WeChatImage.network(shareContent.shareUrl),
                  scene: fluwx.WeChatScene.SESSION,
                );
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
        at top.zibin.luban.Engine.compress(Engine.java:79)
        at top.zibin.luban.Luban.get(Luban.java:152)
        at top.zibin.luban.Luban.access$1100(Luban.java:21)
        at top.zibin.luban.Luban$Builder.get(Luban.java:354)
        at com.jarvan.fluwx.io.ImagesIOIml$compressedByteArray$2.invokeSuspend(ImagesIO.kt:35)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**To Reproduce**

**Which version of Fluwx do you use?**
Tell us the version of your current Fluwx.
`v2.3.0`

**Which device do you run on**
Tell us the device, like BLA-00 and the OS is Android 10.

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/lvyan/flutter
    • Framework revision f30b7f4db9 (11 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lvyan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/lvyan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • SM G9550 (mobile) • 9889db34513850504f • android-arm64 • Android 9 (API 28)
```

**Comment by ningyibo** [comment]
这个问题是怎么解决的？
