### ISSUE TITLE
android 微信双开，分享图片失败

### ISSUE THREAD

**Issue by akindone** [OpenFlutter/fluwx#318]
**Describe the bug**
分享图片:选择双开出来的微信选择完要分享的用户后微信应用退出，查看log是文件权限问题。
设备信息 HUAWEI Mat 20 , EMUI 9.1.0, Android 9,型号 HMA-AL00
```
2020-12-08 14:01:59.358 6018-6018/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.mm, PID: 6018
    java.lang.SecurityException: Permission Denial: opening provider com.jarvan.fluwx.FluwxFileProvider from ProcessRecord{9b8e63e 6018:com.tencent.mm/u128a146} (pid=6018, uid=12810146) that is not exported from UID 10352
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4159)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6845)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2922)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1879)
        at android.content.ContentResolver.query(ContentResolver.java:800)
        at android.content.ContentResolver.query(ContentResolver.java:766)
        at android.content.ContentResolver.query(ContentResolver.java:717)
        at com.tencent.mm.vfs.ContentsSchemeResolver$ContentProviderFileSystem.bgD(SourceFile:85)
        at com.tencent.mm.vfs.q.bgN(SourceFile:231)
        at com.tencent.mm.ui.transmit.SendAppMessageWrapperUI.a(SourceFile:962)
        at com.tencent.mm.ui.transmit.SendAppMessageWrapperUI.a(SourceFile:26788)
        at com.tencent.mm.ui.transmit.SendAppMessageWrapperUI$7.a(SourceFile:718)
        at com.tencent.mm.pluginsdk.ui.applet.o$10.onClick(SourceFile:513)
        at com.tencent.mm.ui.widget.a.d$4.onClick(SourceFile:697)
        at android.view.View.performClick(View.java:6663)
        at android.view.View.performClickInternal(View.java:6635)
        at android.view.View.access$3100(View.java:794)
        at android.view.View$PerformClick.run(View.java:26199)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(Landroid/app/IApplicationThread;Ljava/lang/String;Landroid/os/IBinder;ZI)Landroid/app/ContentProviderHolder;(libmapleservices.so:5063721)
        at android.app.IActivityManager$Stub.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleframework.so:4796909)
        at com.android.server.am.HwActivityManagerService.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmaplehwServices.so:3382169)
        at android.os.Binder.execTransact(IJJI)Z(libmapleframework.so:6087897)
```

搜索进程有2个 "com.tencent.mm"
```
adb shell ps |grep tencent.mm
u128_a146     8770   619 5230908 177448 0                   0 S com.tencent.mm
u128_a146    28671   619 9301352 103968 0                   0 S com.tencent.mm:appbrand1
u0_a146      31093   619 5269872  96040 0                   0 S com.tencent.mm
u0_a146      31219   619 4957156  47192 0                   0 S com.tencent.mm:push
u128_a146    31331   619 4942520  49464 0                   0 S com.tencent.mm:push
u128_a146    31605   619 9672300  56032 0                   0 S com.tencent.mm:appbrand0
```

使用这个方法可以传10M以内的图片，可以作为workround 但是对于其它文件类型，是否还有解决办法
```
WXImageObject imgObj = new WXImageObject(bmp);
```

**To Reproduce**

**Which version of Fluwx do you use?**
    `version: "2.4.1"`

**Which device do you run on**
`HUAWEI Mat 20 , EMUI 9.1.0, Android 9,型号 HMA-AL00`

**Which Flutter do you use?**

Run `flutter doctor` and paste the output here.

**Comment by JarvanMo** [comment]
这个和本项目无关，可以咨询微信官方。10M的图片大小也是微信SDK规定的
