### ISSUE TITLE
跳转微信小程序，把app杀死，微信小程序返回到app是空白页

### ISSUE THREAD

**Issue by xzhbbc** [OpenFlutter/fluwx#348]
android.view.WindowLeaked: Activity com.tencent.mm.plugin.base.stub.WXBizEntryActivity has leaked window DecorView@41f9313[WXBizEntryActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:546)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:329)
        at com.tencent.mm.ui.widget.a.d.show(SourceFile:1018)
        at com.tencent.mm.ui.base.h.a(SourceFile:245)
        at com.tencent.mm.plugin.base.stub.WXBizEntryActivity$7.a(SourceFile:342)
        at com.tencent.mm.pluginsdk.g$2.onSceneEnd(SourceFile:606)
        at com.tencent.mm.aj.t$6.run(SourceFile:542)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.tencent.mm.sdk.platformtools.MMHandler$2.dispatchMessage(SourceFile:350)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

请问这个问题应该如何解决？

**Comment by yy1300326388** [comment]
这个是属于冷启动白屏问题

**Comment by JarvanMo** [comment]
这个问题在3.4.0修复了。具体请参看文档以及demo。

**Comment by wangyan-png** [comment]
> android.view.WindowLeaked: Activity com.tencent.mm.plugin.base.stub.WXBizEntryActivity has leaked window DecorView@41f9313[WXBizEntryActivity] that was originally added here
> at android.view.ViewRootImpl.(ViewRootImpl.java:546)
> at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
> at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
> at android.app.Dialog.show(Dialog.java:329)
> at com.tencent.mm.ui.widget.a.d.show(SourceFile:1018)
> at com.tencent.mm.ui.base.h.a(SourceFile:245)
> at com.tencent.mm.plugin.base.stub.WXBizEntryActivity$7.a(SourceFile:342)
> at com.tencent.mm.pluginsdk.g$2.onSceneEnd(SourceFile:606)
> at com.tencent.mm.aj.t$6.run(SourceFile:542)
> at android.os.Handler.handleCallback(Handler.java:873)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at com.tencent.mm.sdk.platformtools.MMHandler$2.dispatchMessage(SourceFile:350)
> at android.os.Looper.loop(Looper.java:201)
> at android.app.ActivityThread.main(ActivityThread.java:6810)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> 
> 你好你这是从小程序打开的app吗

**Comment by huntrist** [comment]
3.5.0 从微信内的H5调起APP，冷启动安卓端依然会白屏，iOS无法跳转。

**Comment by emptyheadworm** [comment]
都没启动过。你们能启动成功吗

**Comment by JarvanMo** [comment]
4.2.4
