### ISSUE TITLE
IOSNo such module 'fluwx'

### ISSUE THREAD

**Issue by wenboLee** [OpenFlutter/fluwx#39]
`
enbodeMac:flutter_app wenbo$ flutter run
Launching lib/main.dart on iPhone XR in debug mode...
Running pod install...                                       1.0s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_alipay` from `.symlinks/plugins/flutter_alipay/ios`
    -> Fetching podspec for `flutter_picker` from `.symlinks/plugins/flutter_picker/ios`
    -> Fetching podspec for `flutter_webview_plugin` from
    `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `fluwx` from `.symlinks/plugins/fluwx/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `photo_manager` from `.symlinks/plugins/photo_manager/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A AliPay
      A Flutter
      A flutter_alipay
      A flutter_picker
      A flutter_webview_plugin
      A fluttertoast
      A fluwx
      A path_provider
      A photo_manager
      A shared_preferences
      A url_launcher

    Downloading dependencies

    -> Installing AliPay (2.1.2)
      > Copying AliPay from
      `/Users/wenbo/Library/Caches/CocoaPods/Pods/Release/AliPay/2.1.2-2bd35` to
      `Pods/AliPay`

    -> Installing Flutter (1.0.0)

    -> Installing flutter_alipay (0.0.1)

    -> Installing flutter_picker (0.0.1)

    -> Installing flutter_webview_plugin (0.0.1)

    -> Installing fluttertoast (0.0.2)

    -> Installing fluwx (0.0.1)

    -> Installing path_provider (0.0.1)

    -> Installing photo_manager (0.0.1)

    -> Installing shared_preferences (0.0.1)

    -> Installing url_launcher (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include static binaries:
    (/Users/wenbo/Downloads/flutter_app/ios/Pods/AliPay/AlipaySDK.framework)

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/tar
    get_validator.rb:81:in `block (2 levels) in
    verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/tar
    get_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/tar
    get_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/tar
    get_validator.rb:70:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/tar
    get_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/tar
    get_validator.rb:36:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:459:in
    `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:138:in
    `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command/install.rb:
    48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner`
    because no platform was specified. Please specify a platform for this target in your
    Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone XR.
`

**Comment by wenboLee** [comment]
Xcode报错，No such module 'fluwx'
VS code命令运行报错，以上是flutter run后结果

**Comment by wenboLee** [comment]
swift版本是4.2
项目结构没有像example一样，ios和ios_swift没有区分
AppDelegate的代码如下：
`
import UIKit
import Flutter
import fluwx

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {

    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
        ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

    override  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
          return WXApi.handleOpen(url, delegate: FluwxResponseHandler.defaultManager())
      }

    override func application(_ application: UIApplication, handleOpen url: URL) -> Bool {
        return FlutterAlipayPlugin.handleOpen(url);
    }
}

`

**Comment by JarvanMo** [comment]
`The 'Pods-Runner' target has transitive dependencies that include static binaries:
(/Users/wenbo/Downloads/flutter_app/ios/Pods/AliPay/AlipaySDK.framework)。`
和fluwx没关系啊。swift下使用fluwx没关系的，支付宝推荐使用tobais。

**Comment by wenboLee** [comment]
ths😁

**Comment by wenboLee** [comment]
问题解决，原因是，项目本身是在Android环境配置的，移到ios的环境的时候，出现其他问题😑😑

**Comment by lds8988** [comment]
> 问题解决，原因是，项目本身是在Android环境配置的，移到ios的环境的时候，出现其他问题😑😑

请问你是怎么解决这个问题的？
