### ISSUE TITLE
ios15，真机可以跳转微信，但是不会拉起分享人列表

### ISSUE THREAD

**Issue by liuzhanquan20161** [OpenFlutter/fluwx#450]
没有任何报错

**Comment by JarvanMo** [comment]
没有ios15.

**Comment by khizar1556** [comment]
did you resolve the issue @liuzhanquan20161 ?

**Comment by CoderWeiLee** [comment]
> 没有任何报错

请问这个问题解决了吗

**Comment by lhw88860979** [comment]
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- plist (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        from /Users/lianghaowen/Documents/programe/project/saas/module/other/fluwx-5.5.2/ios/wechat_setup.rb:8:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'nkf' (>= 0) among 88 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/lianghaowen/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/opt/homebrew/Cellar/cocoapods/1.16.2/libexec:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2621:in `block in traverse'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2619:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2619:in `traverse'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1086:in `block in find_in_unresolved_tree'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1085:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1085:in `find_in_unresolved_tree'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from /Users/lianghaowen/Documents/programe/project/saas/module/other/fluwx-5.5.2/ios/wechat_setup.rb:8:in `<main>'

不知道是不是导入的问题

**Comment by zwfon** [comment]
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- plist (LoadError) from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require' from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require' from /Users/lianghaowen/Documents/programe/project/saas/module/other/fluwx-5.5.2/ios/wechat_setup.rb:8:in `
> 
> '
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'nkf' (>= 0) among 88 total gem(s) (Gem::MissingSpecError) Checked in 'GEM_PATH=/Users/lianghaowen/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/opt/homebrew/Cellar/cocoapods/1.16.2/libexec:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env`for more information from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2621:in`block in traverse'
> from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2619:in `each' from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2619:in `traverse'
> from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1086:in `block in find_in_unresolved_tree' from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1085:in `each'
> from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1085:in `find_in_unresolved_tree' from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:83:in `require'
> from /Users/lianghaowen/Documents/programe/project/saas/module/other/fluwx-5.5.2/ios/wechat_setup.rb:8:in `'
> 不知道是不是导入的问题

我也有这个问题 在pod install 的时候 执行sudo gem install plist之后都没有作用
